---
- name: Aprovisionament inicial dels clients
  hosts: ansible_cliente
  become: true

  tasks:

    - name: Actualitzar els repositoris i paquets
      apt:
        update_cache: yes
        upgrade: dist
        force_apt_get: yes

    - name: Instal·lar Apache
      apt:
        name: apache2
        state: present

    - name: Crear usuari de prova
      user:
        name: usuari_projecte
        state: present
        shell: /bin/bash

    - name: Crear directori de prova
      file:
        path: /home/usuari_projecte/test_directori
        state: directory
        owner: usuari_projecte
        group: usuari_projecte
        mode: '0755'
