---
- name: Desplegament aplicació web al client
  hosts: ansible_cliente
  become: true

  tasks:

    - name: Instal·lar Nginx
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Instal·lar git
      apt:
        name: git
        state: present

    - name: Assegurar directori web existent
      file:
        path: /var/www/html
        state: directory

    - name: Configurar safe.directory per Git
      git_config:
        name: safe.directory
        scope: global
        value: /var/www/html

    - name: Clonar repositori web
      git:
        repo: https://github.com/cloudacademy/static-website-example.git
        dest: /var/www/html

    - name: Assegurar permisos correctes
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        recurse: yes
